services:
    mysql:
      image: mysql
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: expense_tracker
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      ports:
        - 3306:3306
      